<?php

namespace Database\Seeders;

use App\Models\Part;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        User::create(['name' => 'admin', 'email' => 'admin@stockcontrol.com', 'password' => Hash::make('admin123'), 'role' => 'admin']);
        User::create(['name' => 'user', 'email' => 'user@stockcontrol.com', 'password' => Hash::make('user123'), 'role' => 'user']);

        $parts = [
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'PLATE, FR SEAT BACK SPRING SET','part_number'=>'71173-X7V30','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'PLATE, FR SEAT RECLINING BELT SET','part_number'=>'71373-X7A03 / 71374-X7A03','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'KNOB, RECLINING CONTROL LEVER, RH_LH','part_number'=>'72577-X7A10 / 72578-X7A04','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'CAP, SEAT STAND FRAME','part_number'=>'72345-0K080','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT RECLINING NO. 1 RH','part_number'=>'71833-0K560','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT RECLINING NO. 1 RH / LH','part_number'=>'71833-0K550 / 71834-0K540','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT TRACK UPR RAIL','part_number'=>'72265-0K150','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'HANDLE, RECLINING ADJUSTER RELEASE RH /LH','part_number'=>'72525-0K470 / 72526-0K490','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'LEG SUB-ASSY, RR SEAT CUSHION, RH','part_number'=>'71033-0K110','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'LEG SUB-ASSY, RR SEAT CUSHION, LH','part_number'=>'71033-OK120','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'PROTECTOR, RR SEAT CUSHION EDGE','part_number'=>'71647-X7A01','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT RECLINING NO.2 RH / LH','part_number'=>'71875-0K420 / 71876-OK400','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT RECLINING NO.2 RH / LH','part_number'=>'71875-0K430 / 71876-OK410','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT CUSHION HINGE','part_number'=>'71691-0K590 / 71691-0K630','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'SHIELD, FR SEAT CUSHION RH_LH','part_number'=>'71812-0K640 / 71811-0K550','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'BOARD SUB-ASSY, NO.2 SEAT BACK','part_number'=>'71701-0K110','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'BOARD SUB-ASSY, NO.2 SEAT BACK','part_number'=>'71702-0K120','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT RECLINING, NO.2 INNER RH / LH','part_number'=>'71833-0K500 / 71834-0K500','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT RECLINING RH / LH','part_number'=>'71843-0K360 / 71844-0K340','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT RECLINING','part_number'=>'71843-0K370 / 71844-0K350','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT RECLINING','part_number'=>'71833-0K490 / 71834-0K490','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT CUSHION UNDER. RH','part_number'=>'72927-0K060','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT CUSHION UNDER. LH','part_number'=>'72927-0K050','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'BEZEL, RR SEAT COVER, NO. 1','part_number'=>'71865-X7U00','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'BEZEL, RR SEAT COVER, NO. 2','part_number'=>'71866-X7U00','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'PLATE, RR SEAT','part_number'=>'71779-X7A05','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT CUSHION SIDE RH / LH','part_number'=>'72995-0K680 / 72998-0K260','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT CUSHION SIDE','part_number'=>'72995-0K690 / 72998-0K270','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT CUSHION HINGE, NO.2','part_number'=>'71692-0K610 / 71692-0K630','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT CUSHION HINGE, NO.2','part_number'=>'71692-0K620 / 0K640','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, NO. 2 SEAT LEG RH / LH','part_number'=>'79236-0K290 / 79246-0K270','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT CUSHION HINGE, NO.1','part_number'=>'71691-0k620 / 71691-0K640','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT CUSHION HINGE RH / LH','part_number'=>'71629-0K790 / 71639-0K240','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER RR SEAT CUSHION HINGE LH / RH','part_number'=>'71629-0K800 / 71639-0K250','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT CUSHION HINGE UPR  RH / LH','part_number'=>'71691-0K600 / 71692-0K650','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT CUSHION HINGE LWR RH / LH','part_number'=>'71693-0K820 / 71694-0K790','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'COVER, RR SEAT CUSHION HINGE LWR RH / LH','part_number'=>'71693-0K830 / 71694-0K800','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'7175A-X7V05/7175A-X7V04','part_number'=>'HOOK, SEAT COVER','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'INSERT, ORNAMENT, FR DOOR TRIM, RH / LH','part_number'=>'67781-0K150 / 67782-0K150','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'POCKET, FR DOOR TRIM, RH / LH','part_number'=>'67777-0K200 / 67778-0K200','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'HANDLE, FR DOOR PULL, RH / LH','part_number'=>'74813-0K100 / 74814-0K100','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'INSERT, ORNAMENT SUB-ASSY, RR DOOR TRIM, RH / LH','part_number'=>'67707-0K110 / 67708-0K110','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'INSERT, ORNAMENT, RR DOOR TRIM RH / LH','part_number'=>'67783-0K090 / 67784-0K090','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'POCKET, RR DOOR TRIM, RH / LH','part_number'=>'67787-0K220 / 67778-0K220','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'HANDLE, RR DOOR PULL RH / LH (W/O ILLUMI)','part_number'=>'74815-0K160 / 74816-0K160','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'HANDLE, RR DOOR PULL RH / LH (W/ ILLUMI)','part_number'=>'74815-0K170 / 74816-0K170','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'INSERT, FR DOOR ARMREST RH / LH','part_number'=>'74211 /74212 -X7A38','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'INJECTION PART','part_name'=>'INSERT, RR DOOR ARMREST RH / LH','part_number'=>'74213 /74214 -X7A25','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FELT, SEAT BACK','part_number'=>'7997A - X7A17','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FASTENER, SEAT COVER','part_number'=>'7173A - X7A07','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FELT, SEAT CUSHION','part_number'=>'79978 - X7A26','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FELT, SEAT CUSHION','part_number'=>'79978 - X7A27','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FELT, SEAT BACK','part_number'=>'7997A - X7A23','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FELT, SEAT BACK','part_number'=>'7997A - X7A24','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FELT, SEAT BACK','part_number'=>'7997A - X7A25','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FELT, SEAT CUSHION','part_number'=>'79978 - X7A29','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FELT, SEAT CUSHION','part_number'=>'79978 - X7A30','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FELT, SEAT CUSHION','part_number'=>'79978 - X7A31','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FELT, SEAT BACK','part_number'=>'7997A - X7A26','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FELT, SEAT BACK','part_number'=>'7997A - X7A27','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FELT, SEAT BACK','part_number'=>'7997A - X7A28','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FELT','part_number'=>'79978 - X7A44','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'HANDLE SUB ASSY, RECLINING RELEASE','part_number'=>'72507-0K220','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'STRAP ASSY, RR SEAT LOCK RELEASE','part_number'=>'72690-0K050','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'BAND, SEAT BACK POCKET','part_number'=>'71788 - X7A24','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'STRAP, SEAT COVER','part_number'=>'7178A - X7A66','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'STRAP, SEAT COVER','part_number'=>'7178A - X7A67','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'STRAP, SEAT COVER','part_number'=>'7178A - X7A68','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'STRAP, SEAT COVER','part_number'=>'7178A - X7A69','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'STRAP, SEAT COVER','part_number'=>'7178A - X7A70','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'STRAP, SEAT COVER','part_number'=>'7178A - X7A71','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FELT','part_number'=>'79978-X7A28','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'TRIM SEAT CORNER','part_number'=>'71863 - X7A20','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'TRIM SEAT CORNER','part_number'=>'71863 - X7A21','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'TRIM SEAT CORNER','part_number'=>'71864 - X7A11','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'TRIM SEAT CORNER','part_number'=>'71864 - X7A12','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'TRIM SEAT CORNER','part_number'=>'71727 - X7A36','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'TRIM SEAT CORNER','part_number'=>'71727 - X7A38','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'BAND, RR SEAT CUSHION','part_number'=>'71393 - X7A03','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'BAND, RR SEAT CUSHION','part_number'=>'71393 - X7A14','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'PLATE, RR SEAT CUSHION','part_number'=>'71793 - X7A13','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'PLATE, RR SEAT CUSHION','part_number'=>'71793 - X7A27','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'PLATE, RR SEAT CUSHION','part_number'=>'71793 - X7A28','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FELT, SEAT BACK','part_number'=>'79977-0K340','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'71753 - X7A00','part_number'=>'HOOK, SEAT COVER','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'71864 - X7V43','part_number'=>'TRIM, SEAT CORNER','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'PLATE, SEAT BACK COVER','part_number'=>'71723 - X7A27','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'PLATE, SEAT BACK COVER','part_number'=>'71723 - X7A28','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'PLATE, SEAT BACK COVER','part_number'=>'71723 - X7A29','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'PLATE, SEAT COVER','part_number'=>'71741 - X7A51','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FASTENER, HOOK','part_number'=>'89924-X7271','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FASTENER, PILE','part_number'=>'89924 - X7266','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FASTENER, HOOK','part_number'=>'89924 - X7265','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'PAD, FR FLOOR SILENCER','part_number'=>'58621 - X7A51','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FASTENER, SEAT COVER','part_number'=>'7173A - X7A12','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FASTENER, SEAT COVER','part_number'=>'7173A - X7A13','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FASTENER, SEAT COVER','part_number'=>'7173A-X7A25','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'FASTENER, SEAT COVER','part_number'=>'7173A-X7A31','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'TRIM, SEAT CORNER','part_number'=>'71863-X7A28','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'TRIM, SEAT CORNER','part_number'=>'71863-X7A27','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'TRIM, SEAT CORNER','part_number'=>'71863 - X7A29','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'SEWING PART','part_name'=>'TRIM, SEAT CORNER','part_number'=>'71863 - X7A30','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'SPRING, SUB ASSY FR SEAT BACK','part_number'=>'71053-0K220','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'SPRING, FR SEAT BACK, NO.1','part_number'=>'71441-X7V26','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'BRACKET S/A, RR SEAT CUSHION','part_number'=>'71307-X7A14','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'BRACKET, RR SEAT CUSHION LEG, RR','part_number'=>'71339-X7A08','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'PIN, RR MNL SEAT, LOC','part_number'=>'7U786-X7A01','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'BRACKET S/A, RR SEAT CUSHION','part_number'=>'71307-X7A16','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'BRACKET, RR SEAT CUSHION LEG, RR','part_number'=>'71339-X7A11','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'PIN, RR MNL SEAT, LOC','part_number'=>'7U786-X7A01','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'BRACKET, S/A RR SEAT CUSHION','part_number'=>'71307-X7A15','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'PLATE, BELT SUPPORT','part_number'=>'73118-X7A02','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'PIN','part_number'=>'89923-X7003','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'BRACKET, S/A RR SEAT CUSHION','part_number'=>'71307-X7A17','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'PLATE, BELT SUPPORT','part_number'=>'73118-X7A03','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'PIN','part_number'=>'89923-X7003','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'BRACKET, SUB SEAT CUSHION SIDE','part_number'=>'78724-X7A07','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'PATCH, RR SEAT CUSHION','part_number'=>'71797-X7A32','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'PATCH, RR SEAT CUSHION','part_number'=>'71797-X7A39','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'NUT, WELD','part_number'=>'90174-T0016','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'FRAME SUB ASSY RR SEAT CUSHION PIPE RH','part_number'=>'71019-X7A03','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'FRAME.
RR SEAT CUSHION, RR','part_number'=>'71213-X7A20','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'BRACKET RR SEAT CUSHION','part_number'=>'71327-X7A35','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'FRAME SUB ASSY RR SEAT CUSHION PIPE LH','part_number'=>'71029-X7A03','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'FRAME.
RR SEAT CUSHION, RR','part_number'=>'71213-X7A21','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'BRACKET RR SEAT CUSHION','part_number'=>'71327-X7A36','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'LEG SUB ASSY RR SEAT CUSHION RH','part_number'=>'71033-X7A02','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'LEG MAIN FRAME, NO 1','part_number'=>'71713-X7A02','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'BRACKET RR SEAT CUSHION HINGE','part_number'=>'71243-X7A14','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'BRACKET RR SEAT CUSHION HINGE','part_number'=>'71243-X7A15','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'LEG SUB ASSY RR SEAT CUSHION LH','part_number'=>'71033-X7A03','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'LEG MAIN FRAME, NO 1','part_number'=>'71713-X7A03','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'BRACKET RR SEAT CUSHION HINGE','part_number'=>'71243-X7A16','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'BRACKET RR SEAT CUSHION HINGE','part_number'=>'71243-X7A17','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'WIRE S/A, RR SEAT BACK UPR RH','part_number'=>'71045-X7A14','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'WIRE RR SEAT BACK','part_number'=>'71261-X7A34','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'WIRE RR SEAT BACK','part_number'=>'71261-X7A35','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'WIRE S/A, RR SEAT BACK UPR LH','part_number'=>'71046-X7A03','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'WIRE RR SEAT BACK','part_number'=>'71261-X7A41','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'WIRE RR SEAT BACK','part_number'=>'71261-X7A42','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'WIRE SUB ASSY, RR SEAT BACK RH','part_number'=>'71045-X7A15','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'WIRE RR SEAT BACK','part_number'=>'71261-X7A37','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'WIRE RR SEAT BACK','part_number'=>'71261-X7A36','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'FRAME RR SEAT BACK','part_number'=>'71251-X7A23','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'ROD RR SEAT HINGE CONECTOR','part_number'=>'79169-X7A19','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'ROD RR SEAT HINGE CONECTOR','part_number'=>'79169-X7A18','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'STAY, FR SEAT HEADREST FR','part_number'=>'71911-X7A13','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'STAY, RR SEAT HEADREST  RR1','part_number'=>'71941-X7A40','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'STAY, RR SEAT HEADREST RR1','part_number'=>'71941-X7A41','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'STAY, RR SEAT HEADREST RR2','part_number'=>'71941-X7A43','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'FRAME SUB ASSY NO 1 SEAT BACK RH','part_number'=>'79103-OK410-A','stock'=>3,'min_stock'=>2],
            ['model'=>'737D','commodity'=>'METAL PART','part_name'=>'FRAME SUB ASSY NO 1 SEAT BACK LH','part_number'=>'79104-OK410-A','stock'=>3,'min_stock'=>2],
            ['model'=>'5P45','commodity'=>'INJECTION PART','part_name'=>'CAP, AIR CLEANER','part_number'=>'BW014102-8050','stock'=>6,'min_stock'=>5],
            ['model'=>'5P45V','commodity'=>'INJECTION PART','part_name'=>'CAP, AIR CLEANER','part_number'=>'BW014102-8060','stock'=>10,'min_stock'=>5],
        ];

        foreach ($parts as $p) { Part::create($p); }
    }
}